name: Tests
on: [push]
jobs:
  # Job name
  test-create_users:
    runs-on: ubuntu-latest
    env:
      ADMIN_ID: 1
      PLATE_VALUES: ""
      ROOT_DIR: ""
      ALL_RESULTS_EXCEL_DIR: ""
      USER_IMAGES_DIR: ""
      
    # Create mock database for sql operations.
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        ports:
        # Map PostgreSQL container to host's port 5432.
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@main
      
        # Every job must be separated by a hyphen ('-').
      - name: Setting up Python
        uses: actions/setup-python@main
        with:
          python-version: '3.10.6'
          cache: 'pip'
      
      - name: Installing Dependencies
        run: pip install -r requirements.txt

      - name: pytest -v tests/create_users_test.py
        run: pytest -v tests/create_users_test.py
      
  test-tasks_generator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@main
        with:
          python-version: '3.10.6'
          cache: 'pip'
      - run: pip install -r requirements.txt

      - name: pytest -v tests/tasks_generator_test.py
        run: pytest -v tests/tasks_generator_test.py

  test-tasks_metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@main
        with:
          python-version: '3.10.6'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: pytest -v tests/tasks_metrics_test.py

  test-tasks_new:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@main
        with:
          python-version: '3.10.6'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: pytest -v tests/tasks_new_test.py

