name: Tests
on: [push]
jobs:
  test-create_users:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@main
        with:
          python-version: '3.10.6'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: pytest -v tests/create_users_test.py
  test-tasks_generator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@main
        with:
          python-version: '3.10.6'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: pytest -v tests/tasks_generator_test.py
  test-tasks_metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@main
        with:
          python-version: '3.10.6'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: pytest -v tests/tasks_metrics_test.py
  test-tasks_new:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@main
        with:
          python-version: '3.10.6'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: pytest -v tests/tasks_new_test.py

