name: Tests
on: [push]
jobs:
  test-create-users:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@main
        with:
          python-version: '3.10.6'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: pytest tests/create_users_test.py
  test-tasks_generator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@main
        with:
          python-version: '3.10.6'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: pytest tests/tasks_generator_test.py
