name: Tests
on: [push]
jobs:
  test-create-users:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@main
        with:
          python-version: '3.10.6'
          cache: 'pip'
      - run: python --version
      - run: python3.10 --version
      - run: python3 --version
      - run: pip freeze
      - run: pip install -r requirements.txt
      - run: pip freeze
